version: 0.2

env:
  variables:
    # enables continuous integration settings where applicable
    CI: true
    PORT: 5000

phases:
  install:
    commands:
      # runs package install from yarn
      - npx yarn install
  pre_build:
    commands:
      - npm run test
      - npx pm2 start index.js
  build:
    commands:
      - #sleep 10
  post_build:
    commands:
      # handles a conflict between npm and yarn, must find more elegant solution
      - curl localhost:5000
      - rm -rf ./node_modules
artifacts:
  files:
    - '**/*'
